# .github/workflows/release-tag.yml

name: Create Version Tag on Package Update

on:
  push:
    branches:
      - main
      - "dev"
      - "qa"
    paths:
      - "package.json"

jobs:
  tag-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js (for jq, if not pre-installed, though usually it is)
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Tag on Package Version Change
        uses: ./.github/actions/tag-on-package-version-change
        with:
          git-user-name: "My Custom Bot"
          git-user-email: "bot@example.com"
          branch-suffix-map: |
            {
              "main": "",
              "dev": "-alfa",
              "qa": "-beta",
            }
            # You can add any branch-to-suffix mapping here.
            # If a branch is not listed, it will get no suffix (empty string).
