# .github/workflows/release-tag.yml

name: Create Version Tag
on:
  push:
    branches: [main, dev, qa, prod, test-code]
    paths: ["package.json"]

jobs:
  tag-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Get PR Author Info
        id: pr-author
        run: |
          echo "AUTHOR_NAME=${{ github.event.sender.login }}" >> $GITHUB_ENV
          echo "AUTHOR_EMAIL=${{ github.event.sender.email }}" >> $GITHUB_ENV
          echo "COMMIT_SHA=${{ github.sha }}" >> $GITHUB_ENV

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ./.github/actions/tag-on-package-version-change
        with:
          git-user-name: ${{ env.AUTHOR_NAME }}
          git-user-email: ${{ env.AUTHOR_EMAIL }}
          branch-suffix-map: |
            {
              "main": "",
              "test-code": "-pre-alfa",
              "dev": "-alpha",
              "qa": "-beta",
              "prod": "-rc"
            }

      - name: Print Tag Creation Info
        run: |
          echo "Tag created by: ${{ env.AUTHOR_NAME }}"
          echo "Commit SHA: ${{ env.COMMIT_SHA }}"
          echo "Branch: ${{ github.ref_name }}"
